### ISSUE TITLE
Incorrect use of Craft.Net

### ISSUE THREAD

**Issue by ddevault** [AlinaNova21/SharpMinecraftLibrary#10]
Hello there,

Can you go ahead and add the Craft.Net license into your repository? Dropping the license from the code is a violation of the terms.

Choices:
- Remove Craft.Net from your repository

or
- Add [this file](https://github.com/SirCmpwn/Craft.Net/blob/master/LICENSE) somewhere that makes it obvious it belongs with Craft.Net.

Obviously, the second solution works best for all involved. Thanks!

**Comment by AlinaNova21** [comment]
Sorry about that, I thought it was in there. It has been added now.

**Comment by ddevault** [comment]
Thanks!
