### ISSUE TITLE
Packet Errors

### ISSUE THREAD

**Issue by TTGX12** [AlinaNova21/SharpMinecraftLibrary#9]
I am getting a lot of packet errors upon connecting to any server while using a valid login.

Also,

Error   4   The name 'Slot' does not exist in the current context   C:\Users\Administrator\Desktop\MCS\MinecraftLibrary\Packet.cs   320 9   MinecraftLibrary
Error   2   The type or namespace name 'Slot' could not be found (are you missing a using directive or an assembly reference?)  C:\Users\Administrator\Desktop\MCS\MinecraftLibrary\Packet.cs   319 10  MinecraftLibrary

Error   3  
The type or namespace name 'Slot' could not be found (are you missing a using directive or an assembly reference?)  C:\Users\Administrator\Desktop\MCS\MinecraftLibrary\Packet.cs   319 24  MinecraftLibrary

**Comment by AlinaNova21** [comment]
This should be fixed in later versions.

**Comment by TTGX12** [comment]
## 

Please don't use profanity.
